# Use Rails secret.yml, but if you want something different...

SOMETHING_KEY: ""
SOMETHING_SECRET: ""

Add this to application.rb:

    # Environment variables for <whatever>
    config.before_configuration do
      env_file = File.join(Rails.root, 'config', 'local_env.yml')
      YAML.load(File.open(env_file)).each do |key, value|
        ENV[key.to_s] = value
      end if File.exists?(env_file)
    end

For credentials:

ENV['SOMETHING_KEY']
ENV['SOMETHING_SECRET']
